<?php
/**
 *  Implementation of hook_init()
 *  - Includes the required files at time of execution or initialization
 */
function mcny_objects_init() {
    drupal_add_js(drupal_get_path('module', 'mcny_objects') . '/js/mcny_objects.js', array('scope' => 'footer'));
}

/**
 *  Implements hook_block_info()
 *  - Initialize the blocks with information
 */
function mcny_objects_block_info() {
    $blocks = array();
    $blocks['mcny_objects_images'] = array(
        'info' => t('MCNY: Objects and Images'),
        'cache' => DRUPAL_CACHE_PER_ROLE,
        //'status' => 1
    );
    return $blocks;
}

/**
 *  Implements hook_block_view()
 *  - Create the views for blocks
 */
function mcny_objects_block_view($delta = '') {
    $block = array();
    switch ($delta) {
        case 'mcny_objects_images':
            $objects_exh = mcny_objects_get_exhibition(arg(1));
            $hasSlides = ($objects_exh['total_slides'] >= 1) ?  true : false;
            if(user_access('access content') && $hasSlides) { //good idea to check user perms here
                $block['subject'] = 'Objects and Images';
                $block['content'] = theme('block__mcny_objects_images');
            }
            break;
    }
    return $block;
}

/**
 *  Implements the theme hook.
 *  - To override the theme for blocks
 */
function mcny_objects_theme() {
    $items['block__mcny_objects_images'] = array (
        'template' => 'block--mcny_objects_images',   // here comes your template name
        'original hook' => 'block',
        'path' => drupal_get_path('module', 'mcny_objects') . '/templates',
    );
    return $items;
}

/**
 *  Implements hook_menu()
 *  - Create the silent route to execute the ajax request
 */
function mcny_objects_menu() {
    $items['ajax/open_objects_modal'] = array (
        'title' => 'Get Objects Images',
        'page callback' => 'mcny_objects_open_object_modal',
        'access arguments' => array ('access content'),
        'type' => MENU_CALLBACK,
    );
    return $items;
}

/**
 *  Ajax Call Back
 *  - Returns the desired activists images data in JSON
 */
function mcny_objects_open_object_modal() {
    // Get currently logged in user.
    $result = mcny_objects_get_modal_detal($_POST['id']);
    drupal_json_output($result);
}

/*
 *  Returns the activists by current exhibition node
 *  - Call back for showing the activists images
 */
function mcny_objects_get_modal_detal ($nid, $type = 'object_and_images'){
    $node = null;
    $query = new EntityFieldQuery();

    $query->entityCondition('entity_type', 'node')
        ->propertyCondition('nid', $nid)
        ->propertyCondition('status', NODE_PUBLISHED)
        ->entityCondition('bundle', $type);
    $queryResult = $query->execute();

    $nids = (isset($queryResult['node'])) ? array_keys($queryResult['node']) : null;
    $nodes = entity_load('node', $nids);

    //$currentNode = (isset($nodes[0])) ? $nodes[$nids[0]] : $nodes;
    $currentNode = $nodes[$nids[0]];
    $imageWithAutoScale = image_style_url('activist_thumbnail_large', $currentNode->field_object_image['und'][0]['uri']);

    $nodes[$nids[0]]->field_object_image['und'][0]['uri_scaled'] = $imageWithAutoScale;

    return $nodes;
}

/*
 *  Returns the activists by current exhibition node
 *  - Call back for showing the activists images
 */
function mcny_objects_get_exhibition ($nid, $thumbnailsPerSlide = 1, $type = 'object_and_images'){
    $node = null;
    $query = new EntityFieldQuery();

    $query->entityCondition('entity_type', 'node')
        ->propertyCondition('status', NODE_PUBLISHED)
        ->entityCondition('bundle', $type)
        ->fieldOrderBy('field_object_weight', 'value', 'ASC')
        ->fieldCondition('field_object_exhibition_ref', 'target_id', $nid);
    $queryResult = $query->execute();

    $nids = (isset($queryResult['node'])) ? array_keys($queryResult['node']) : null;
    $nodes = entity_load('node', $nids);
    $totalNodes = count($nodes);

    $results = array();
    $results['nodes'] = $nodes;
    $results['node_ids'] = $nids;
    $results['total_nodes'] = $totalNodes;

    $slides = array();
    $totalRows = round($totalNodes / $thumbnailsPerSlide);
    for($i=1; $i <= $totalRows; $i++){
        $count = 1;
        foreach($nodes as $k => $n){
            if($count <= $thumbnailsPerSlide) {
                $slides[$i][] = $n;
                $count++;
                unset($nodes[$k]);
            }
        }
    }

    $results['slides'] = $slides;
    $results['total_slides'] = count($slides);

    return $results;
}